{% set name = "tpi" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8275325c3f5a67590170b55e16854acbae7248c46e933255affbcb6a6643de5b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tpi = tpi.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=3.4
    - toml
  run:
    - python >={{ python_min }}
    - asyncssh
    - funcy
    - jinja2 >=2.0.0
    - miutil >=0.7.0
    - python-terraform >=0.10.1
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - tpi
    - tpi.bin
    - tpi.terraform
  commands:
    - tpi -h

about:
  home: https://github.com/iterative/tpi
  license: Apache-2.0
  license_family: Apache
  license_file: LICENCE
  summary: Python wrapper for terraform-provider-iterative

  description: |
    Python wrapper for https://github.com/iterative/terraform-provider-iterative.
    Automatically downloads platform-dependent terraform binaries and exposes a Python API.

extra:
  recipe-maintainers:
    - casperdcl
    - shcheklein
